services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - id.carsties.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somethingreallysecret
      - NEXTAUTH_URL=http://app.carsties.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://id.carsties.com
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
      - VIRTUAL_HOST=app.carsties.com
      - VIRTUAL_PORT=3000
    networks:
      - backend-network

networks:
  backend-network:
    external: true
